### ISSUE TITLE
Any plans to bring this upto date with v7?

### ISSUE THREAD

**Issue by braindeaf** [fzaninotto/DependencyWheel#19]
Just found this and wanted to use it in a new project but I think it's not loading in a compatible way. I am new to d3 so I can't just go about upgrading but I can try my hand.

**Comment by fzaninotto** [comment]
Hi, and thanks for your question.

I don't use this library in production for now, so I have no plan to update it in the foreseeable future. 

I'll accept a PR to upgrade it to recent versions of d3, though.
