### ISSUE TITLE
Add click action to highlight instead of only mouse over

### ISSUE THREAD

**Issue by grillorafael** [fzaninotto/DependencyWheel#7]
When the dependency wheel is too big it's hard to keep the mouse over the element.

It would be good to add this in text click/hover as well.

What do you think?

**Comment by fzaninotto** [comment]
If it's hard to hover, it's also hard to click, no? Would you have an example of "too big" wheel?

**Comment by grillorafael** [comment]
In that case the label click would do the job. I'll add an image here in a
bit. Just woke up hahaha

On Monday, September 14, 2015, Francois Zaninotto <notifications@github.com>
wrote:

> If it's hard to hover, it's also hard to click, no? Would you have an
> example of "too big" wheel?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fzaninotto/DependencyWheel/issues/7#issuecomment-140046024>
> .
>


-- 
Rafael Grillo Abreu
+55 21 99461-1339
LinkedIn <https://www.linkedin.com/profile/view?id=89764578>
*Developer*

**Comment by grillorafael** [comment]
![screencapture-localhost-3000-1442159440798](https://cloud.githubusercontent.com/assets/1812267/9849858/1eb8721e-5ac5-11e5-99d5-aaf98ce29a2c.png)

**Comment by grillorafael** [comment]
![screencapture-localhost-3000-1442159440798](https://cloud.githubusercontent.com/assets/1812267/9849918/94541d3e-5ac5-11e5-98f7-5a764c541f8c.png)

**Comment by grillorafael** [comment]
Those tiny elements are very hard to hover.

In fact this are two things instead of just one.

If we bind to click element/label we can add scroll to the box where the dependency wheel is in and then we can scroll without losing focus of what we want.

And it will be easier to focus elements by clicking on their labels.

**Comment by fzaninotto** [comment]
good idea, the labels should be hoverable, too.

**Comment by fzaninotto** [comment]
Fixed by #9

**Comment by grillorafael** [comment]
Good! Thanks @katrotz @fzaninotto
